// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efsmzslkgxrdwcjnkjbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmc216c2xrZ3hyZHdjam5ramJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMTY3NTMsImV4cCI6MjA1NDc5Mjc1M30.X0NaUv_-s6Gx35f7LA3ZFKwr7AcVHKS9t_xqCSo1kbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);